# Generated by Django 5.2.6 on 2025-09-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_optimize_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='E.164 format, e.g. +989123456789', max_length=15, null=True, unique=True),
        ),
    ]
