# Generated by Django 5.2.6 on 2025-09-22 22:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_type', models.CharField(choices=[('main', 'منوی اصلی'), ('footer', 'منوی فوتر'), ('quick_access', 'دسترسی سریع'), ('customer_service', 'خدمات مشتریان')], max_length=20, verbose_name='نوع منو')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url', models.CharField(help_text='لینک داخلی (مثال: /products/) یا خارجی', max_length=200, verbose_name='لینک')),
                ('icon_class', models.CharField(blank=True, help_text='کلاس آیکون Bootstrap', max_length=50, verbose_name='کلاس آیکون')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_external', models.BooleanField(default=False, help_text='آیا این لینک خارجی است؟', verbose_name='لینک خارجی')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز کردن در تب جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['menu_type', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('announcement_type', models.CharField(choices=[('info', 'اطلاعیه'), ('warning', 'هشدار'), ('success', 'موفقیت'), ('promotion', 'تخفیف'), ('maintenance', 'تعمیرات')], max_length=20, verbose_name='نوع اعلان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی')),
                ('show_in_navbar', models.BooleanField(default=False, verbose_name='نمایش در نوار ناوبری')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, help_text='اختیاری - اگر مشخص نشود، اعلان تا زمان غیرفعال کردن نمایش داده می\u200cشود', null=True, verbose_name='تاریخ پایان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اعلان سایت',
                'verbose_name_plural': 'اعلانات سایت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(help_text='نام رسمی سایت', max_length=100, verbose_name='نام سایت')),
                ('site_tagline', models.TextField(blank=True, help_text='شعار یا توضیح کوتاه سایت', max_length=200, verbose_name='شعار سایت')),
                ('site_domain', models.CharField(help_text='دامنه اصلی سایت (مثال: istanbulplus.ir)', max_length=100, verbose_name='دامنه سایت')),
                ('logo_high_quality', models.ImageField(help_text='لوگو با کیفیت بالا برای نمایش در صفحات اصلی', upload_to='logos/', verbose_name='لوگو کیفیت بالا')),
                ('logo_low_quality', models.ImageField(help_text='لوگو با کیفیت پایین برای بارگذاری سریع', upload_to='logos/', verbose_name='لوگو کیفیت پایین')),
                ('favicon', models.ImageField(blank=True, help_text='آیکون کوچک برای تب مرورگر', upload_to='logos/', verbose_name='فاویکون')),
                ('default_meta_description', models.TextField(help_text='توضیحات پیش\u200cفرض برای متا تگ description', max_length=160, verbose_name='توضیحات پیش\u200cفرض SEO')),
                ('default_meta_keywords', models.TextField(blank=True, help_text='کلمات کلیدی پیش\u200cفرض برای SEO', max_length=200, verbose_name='کلمات کلیدی پیش\u200cفرض')),
                ('default_og_image', models.ImageField(blank=True, help_text='تصویر پیش\u200cفرض برای اشتراک\u200cگذاری در شبکه\u200cهای اجتماعی', upload_to='seo/', verbose_name='تصویر پیش\u200cفرض Open Graph')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این تنظیمات فعال است؟', verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('about', 'درباره ما'), ('terms', 'شرایط استفاده'), ('privacy', 'حریم خصوصی'), ('shipping', 'شیوه\u200cهای ارسال'), ('return', 'مرجوعی کالا'), ('guide', 'راهنمای خرید'), ('support', 'پشتیبانی'), ('footer_description', 'توضیحات فوتر'), ('hero_title', 'عنوان اصلی صفحه اول'), ('hero_description', 'توضیحات صفحه اول')], max_length=30, unique=True, verbose_name='نوع محتوا')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(help_text='محتوای کامل (پشتیبانی از HTML)', verbose_name='محتوا')),
                ('short_description', models.TextField(blank=True, help_text='خلاصه محتوا برای نمایش در لیست\u200cها', max_length=300, verbose_name='توضیح کوتاه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محتوای سایت',
                'verbose_name_plural': 'محتوای سایت',
                'ordering': ['content_type'],
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_products', models.PositiveIntegerField(default=0, verbose_name='تعداد کل محصولات')),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='تعداد کل مشتریان')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='تعداد کل سفارشات')),
                ('trust_badges', models.JSONField(default=list, help_text='لیست نشان\u200cهای اعتماد (نماد الکترونیکی، مجوزها و...)', verbose_name='نشان\u200cهای اعتماد')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تأسیس')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='شماره مجوز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'آمار سایت',
                'verbose_name_plural': 'آمار سایت',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('linkedin', 'لینکدین'), ('twitter', 'توییتر'), ('facebook', 'فیس\u200cبوک'), ('youtube', 'یوتیوب'), ('tiktok', 'تیک\u200cتاک'), ('aparat', 'آپارات')], max_length=20, unique=True, verbose_name='پلتفرم')),
                ('url', models.URLField(help_text='لینک کامل صفحه در شبکه اجتماعی', verbose_name='لینک')),
                ('display_name', models.CharField(help_text='نام نمایشی در فوتر', max_length=100, verbose_name='نام نمایشی')),
                ('icon_class', models.CharField(help_text='کلاس آیکون Bootstrap (مثال: bi-instagram)', max_length=50, verbose_name='کلاس آیکون')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='باز کردن در تب جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'لینک شبکه اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای شبکه\u200cهای اجتماعی',
                'ordering': ['display_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_type', models.CharField(choices=[('phone', 'تلفن'), ('mobile', 'موبایل'), ('email', 'ایمیل'), ('whatsapp', 'واتساپ'), ('telegram', 'تلگرام'), ('address', 'آدرس'), ('working_hours', 'ساعات کاری')], max_length=20, verbose_name='نوع تماس')),
                ('title', models.CharField(help_text='عنوان نمایشی (مثال: تلفن تماس)', max_length=100, verbose_name='عنوان')),
                ('value', models.CharField(help_text='مقدار واقعی (شماره، ایمیل، آدرس و...)', max_length=200, verbose_name='مقدار')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش در فوتر', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_clickable', models.BooleanField(default=True, help_text='آیا این اطلاعات قابل کلیک است؟ (برای تلفن، ایمیل و...)', verbose_name='قابل کلیک')),
                ('icon_class', models.CharField(blank=True, help_text='کلاس آیکون Bootstrap (مثال: bi-telephone)', max_length=50, verbose_name='کلاس آیکون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اطلاعات تماس',
                'verbose_name_plural': 'اطلاعات تماس',
                'ordering': ['display_order', 'contact_type'],
                'unique_together': {('contact_type', 'value')},
            },
        ),
    ]
