# Generated by Django 5.2.6 on 2025-09-22 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='عنوان اصلی کارت (مثال: تور ویژه VIP)', max_length=100, verbose_name='عنوان کارت')),
                ('subtitle', models.CharField(blank=True, help_text='زیرعنوان یا توضیح کوتاه', max_length=200, verbose_name='زیرعنوان')),
                ('price', models.CharField(blank=True, help_text='قیمت یا اطلاعات قیمت (مثال: از 500,000 تومان)', max_length=50, verbose_name='قیمت')),
                ('image', models.ImageField(help_text='تصویر نمایشی کارت', upload_to='hero_cards/', verbose_name='تصویر کارت')),
                ('link_url', models.CharField(blank=True, help_text='لینک مقصد (مثال: /products/vip-tour/)', max_length=200, verbose_name='لینک')),
                ('link_text', models.CharField(default='مشاهده', help_text='متن دکمه لینک', max_length=50, verbose_name='متن لینک')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش کارت\u200cها', verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز کردن در تب جدید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کارت Hero',
                'verbose_name_plural': 'کارت\u200cهای Hero',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('background_type', models.CharField(choices=[('gradient', 'گرادیان'), ('solid', 'رنگ یکنواخت'), ('image', 'تصویر')], default='gradient', max_length=20, verbose_name='نوع پس\u200cزمینه')),
                ('background_color', models.CharField(default='#667eea', help_text='کد رنگ hex (مثال: #667eea)', max_length=7, verbose_name='رنگ پس\u200cزمینه')),
                ('background_gradient_start', models.CharField(default='#667eea', help_text='رنگ شروع گرادیان', max_length=7, verbose_name='شروع گرادیان')),
                ('background_gradient_end', models.CharField(default='#764ba2', help_text='رنگ پایان گرادیان', max_length=7, verbose_name='پایان گرادیان')),
                ('background_image', models.ImageField(blank=True, help_text='تصویر پس\u200cزمینه (در صورت انتخاب نوع تصویر)', upload_to='hero_backgrounds/', verbose_name='تصویر پس\u200cزمینه')),
                ('animation_enabled', models.BooleanField(default=True, verbose_name='فعال\u200cسازی انیمیشن')),
                ('animation_speed', models.CharField(choices=[('slow', 'آهسته'), ('normal', 'عادی'), ('fast', 'سریع')], default='normal', max_length=10, verbose_name='سرعت انیمیشن')),
                ('show_particles', models.BooleanField(default=True, verbose_name='نمایش ذرات متحرک')),
                ('show_cards', models.BooleanField(default=True, verbose_name='نمایش کارت\u200cها')),
                ('cards_count', models.PositiveIntegerField(default=3, help_text='تعداد کارت\u200cهای نمایشی (حداکثر 6)', verbose_name='تعداد کارت\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات Hero',
                'verbose_name_plural': 'تنظیمات Hero',
            },
        ),
    ]
